# Generated by Django 6.0.2 on 2026-08-02 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_time_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('EVENT_CREATE', 'Event Created'), ('EVENT_UPDATE', 'Event Updated'), ('EVENT_DELETE', 'Event Deleted'), ('CLUB_UPDATE', 'Club Settings Updated'), ('CLUB_CREATE', 'Club Created'), ('USER_ACCESS', 'User Access Updated')], max_length=50)),
                ('entity_type', models.CharField(help_text="e.g. 'Event', 'Club', 'User'", max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
