# Generated by Django 6.0.2 on 2026-08-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='encrypted_sender_password',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='sender_email',
            field=models.EmailField(blank=True, help_text='Custom sender email for club notifications', max_length=254, null=True),
        ),
    ]
